### ISSUE TITLE
Extend/shrink client down and up not working

### ISSUE THREAD

**Issue by MohamedIrfanAM** [raven2cz/awesomewm-config#1]
Extend client down and up not working, it just resizes it horizontally.
Please help

**Comment by raven2cz** [comment]
Which layout do you mean? Treetile or machi-layout? If Treetile Win+Alt + arrows change size of the clients. In machi-layout, it's Win+holding of right mouse button, or alternative Win+/ to edit mode and use Shift+CTRL and arrows.

**Comment by MohamedIrfanAM** [comment]
> Which layout do you mean? Treetile or machi-layout? If Treetile Win+Alt + arrows change size of the clients. In machi-layout, it's Win+holding of right mouse button, or alternative Win+/ to edit mode and use Shift+CTRL and arrows.

No, I am using normal Tile(master and stack)  layout that came default with awesomeWM `awful.layout.suit.tile`

**Comment by MohamedIrfanAM** [comment]
I am a newbie to Lua and awesome, is it possible to do with the default `Tile Layout` ?? please help
Treetile function works with Horizontal resize(left , right), i haven't included treetile in my config

**Comment by raven2cz** [comment]
> I am a newbie to Lua and awesome, is it possible to do with the default `Tile Layout` ?? please help
> Treetile function works with Horizontal resize(left , right), i haven't included treetile in my config

Awesomewm according this table:
https://wiki.archlinux.org/index.php/Comparison_of_tiling_window_managers

belongs to the Dynamic management style of Tiling Window Managers. In the basic/standard form, the list of standard layouts of awesomewm are dynamic layouts with exact given behavior. Each of them is another type of work + Next few layouts by Lain extension. Few of them have few possibility for resizing, but still keep the business logic of the active layout.
It is difference against Manual Tiling Window Managers where is behavior between windows given to user hands.

I'm in the middle of it. My best layout is partial dynamic and partial manual and partial floating. It is reason why I'm using machi-layout which allows me all workflows which I need. 
For main bigger terminal work I'm using treetile layout with few modifications. 
And for specific apps and few developments components I'm still using floating layout (standard normal layout known from other desktop environments). But 80% of my work is in the machi-layout.

If you have more questions, it is better to use reddit group r/awesomewm, there are many users of this beautiful WM. It needs to study this WM, but after understanding, there is no better solution for WM...

**Comment by MohamedIrfanAM** [comment]
I actually solved this by adding a function to resize clients. I don't like manual tiling WMs, that's why I don't like to add treetile layout. Anyway my problem is fixed now :)
Thank you for responding :)

**Comment by raven2cz** [comment]
> I actually solved this by adding a function to resize clients. I don't like manual tiling WMs, that's why I don't like to add treetile layout. Anyway my problem is fixed now :)
> Thank you for responding :)

In any way, I add visualization of the hidden machi layout feature. To understand what I mean. The link to video is in the Readme.md
https://www.youtube.com/watch?v=Z0muY_lfFZU
