### ISSUE TITLE
changing window shapes

### ISSUE THREAD

**Issue by XLramones** [raven2cz/awesomewm-config#3]
Is there a way to change the default shape of windows from rounded to square?

**Comment by raven2cz** [comment]
> Is there a way to change the default shape of windows from rounded to square?

Sorry, I haven't activated notification for issues. I expect that it is not relevant yet after the month. But yes, of course. It is configuration of nice plugin. The configuration is placed in the fishlive common library `fishlive/plugins/init.lua`  section `plugins.createTitlebarsNiceLib()` change `titlebar_radius` from 11 to 3.
