### ISSUE TITLE
How u make smooth transition animations?

### ISSUE THREAD

**Issue by AdsonCicilioti** [raven2cz/awesomewm-config#4]
Hello bro!

I watched the trailer and was very impressed with everything, but what caught my attention the most was the smoothness of the animations. The way one window gives way to another, changing and adjusting the size.

I need this, tell me how to get this result.

Thank you very much.

**Comment by raven2cz** [comment]
> Hello bro!
> 
> I watched the trailer and was very impressed with everything, but what caught my attention the most was the smoothness of the animations. 

The picom fork which was used for few video chapters:
https://github.com/pijulius/picom

> The way one window gives way to another, changing and adjusting the size.

I'm not sure here which effects or behavior do you mean. But still several presented animations was picom pijulius.

There is one disadvantage that the animation cannot be easily stop for manual movement of floating windows. I wish this feature, but it is not available and there is no "active" development.

> 
> I need this, tell me how to get this result.
> 
> Thank you very much.
